### PR TITLE
Use the encryptAndEncode and decodeAndDecrypt funcs

### LINKED ISSUE #62: tfState encryption should use encryptAndEncode func
Currently we only use the `encryptAndEncode` function when setting sensitive attributes and not when saving state - although it has the same code https://github.com/lawrencegripper/tfoperatorbridge/blob/4c28a18acda3c9dfb38e6525a8bcd2ab89abea6c/reconcile.go#L267

### PR DESCRIPTION
**Pull request by jjcollinge**
closes #62

### CODE REVIEW

**Comment by lawrencegripper** [comment]
@jjcollinge I noticed that the integration tests on the builds are skipping the 2 encryption tests. Going to create a PR to add those tests into the build by setting the `TF_STATE_ENCRYPTION_KEY` if that sounds like a good plan?

**Comment by lawrencegripper** [comment]
PR here: https://github.com/lawrencegripper/tfoperatorbridge/pull/66

**Comment by jjcollinge** [comment]
Ah thanks - Yh happy to bring it into this one

**Comment by jjcollinge** [comment]
@lawrencegripper just looking at this PR - CI seems to be running all tests as we set the env var as a secret:
` SUCCESS! -- 27 Passed | 0 Failed | 0 Pending | 0 Skipped`

**Comment by lawrencegripper** [comment]
Your totally right I was being an idiot - sorry

**Pull request merged**
